/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Title = string;
export type Subtitle = string;
export type HeaderFontSize = string;
export type HeaderBackgroundColor = string;
export type RowHeight = string;
/**
 * You can describe the border in this way: ''1px solid red''
 */
export type RowBorder = string;
export type HeaderLabel = string;
export type DataType = "state" | "string" | "number" | "boolean" | "button" | "image";
/**
 * Number of digits after the decimal point.
 */
export type NumberPrecision = number;
export type ColumnWidth = number;
export type FontSize = string;
/**
 * eg. 800 for bold and 100 for light font.
 */
export type FontWeight = string;
export type FontColor = string;
/**
 * You can describe the border in this way: '1px solid red'
 */
export type CellBorder = string;
/**
 * Applicable for datatype 'state' fields only. Describe the State Map as an alternating list like this: "'ONLINE': 'green', 'DISCONNECTED', 'red'"
 */
export type StateMap = string;
export type Values = string[];
/**
 * Choose the columns and define how they should be displayed.
 */
export type ColumnDefinition = {
  header: HeaderLabel;
  type?: DataType;
  precision?: NumberPrecision;
  width?: ColumnWidth;
  fontSize?: FontSize;
  fontWeight?: FontWeight;
  color?: FontColor;
  border?: CellBorder;
  stateMap?: StateMap;
  values?: Values;
  [k: string]: unknown;
}[];

export interface TableChartConfiguration {
  settings?: TableSettings;
  columns?: ColumnDefinition;
  [k: string]: unknown;
}
export interface TableSettings {
  title?: Title;
  subTitle?: Subtitle;
  headerFontSize?: HeaderFontSize;
  headerBackground?: HeaderBackgroundColor;
  rowHeight?: RowHeight;
  rowBorder?: RowBorder;
  [k: string]: unknown;
}
